### ISSUE TITLE
MLM2 GSPro double hit reads

### ISSUE THREAD

**Issue by willschabel** [kenjdavidson/gspro-connector#2]
I'm noticing quite often while playing when I hit the ball will read correctly, settle, and then re-apply the same hit again.

I'm assuming this is happening due to a change on the screen of some sort causing the program to re-read the same data twice or more.

A good stop gap solution maybe to add a setting to stop and start the data recognition with a keybind. Obviously when enabled it will wait for a change, but once enabled will automatically disable after the first read, this will allow the user to enable reading once they are ready to hit again.

**Comment by kenjdavidson** [comment]
Hey so thanks. But this doesn't support mlm2, to be honest it doesn't really support anything. Unless you've written your own mlm2 connector, in which case cool, and I'm down to help, but not really an issue?

**Comment by willschabel** [comment]
Yeah my bad, meant to post it on Springbok's repo, not yours. Whoops.

**Comment by kenjdavidson** [comment]
Right on.
